### ISSUE TITLE
drivers/amlogic/dvb_tv

### ISSUE THREAD

**Issue by stpf99** [chewitt/linux#23] opened 2023-06-13 12:23 UTC
https://github.com/endlessm/linux-meson/tree/master/drivers/amlogic/dvb_tv                                                                --linux_meson
https://github.com/afl1/LibreELEC.tv/tree/99f117035d49480a90f298d119f189f999bb6fd3/projects/S905/dvb_tv       --afl1
https://github.com/AlexELEC/linux-amlogic/tree/aml_dvb/drivers/amlogic/dvb_tv                                                             --alexelec

what is neccesary to include pro way in new kernel this "demux" code to some place possible in driver/media amlogic or arch agnostic specific folder and integrate your effort in branch "dvb-suck" for test  ,... (:D-;:::==,'

**Comment by chewitt** [comment] 2023-06-13 13:10
Closing as a duplicate of #9 - and because this is not a chat/message board

**Closed as completed by chewitt** 2023-06-13 13:10 UTC
